name: Build e Deploy Laravel Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  laravel-deploy:
    name: Build Laravel app (backend-php)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: expense/backend-php

    steps:
      - name: 📥 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🧰 Configurar PHP com Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, ctype, fileinfo, json, openssl, pdo, tokenizer, xml, curl, gd
          coverage: none

      - name: 📦 Instalar dependências
        run: composer install --no-dev --optimize-autoloader

      - name: 🔐 Copiar .env de produção
        run: cp .env.production .env

      - name: 🔑 Gerar chave do aplicativo
        run: php artisan key:generate

      - name: 🧠 Gerar caches Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # [Opcional] DEPLOY VIA SFTP — configure os secrets
      - name: 🚀 Deploy via SFTP
        uses: pressidium/lftp-action@v1.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          user: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          localDir: 'expense/backend-php/'
          remoteDir: '/home1/isacag00/novemax/'
          args: '-e -n'

      - name: 🔐 Gerar arquivo .env
        run: |
          echo "APP_NAME=SCD" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=${{ secrets.ENV_APP_KEY }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://scd.novemax.com.br" >> .env

          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.ENV_DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.ENV_DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.ENV_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.ENV_DB_PASSWORD }}" >> .env

          echo "MAIL_MAILER=smtp" >> .env
          echo "MAIL_HOST=${{ secrets.ENV_MAIL_HOST }}" >> .env
          echo "MAIL_PORT=587" >> .env
          echo "MAIL_USERNAME=${{ secrets.ENV_MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.ENV_MAIL_PASSWORD }}" >> .env
          echo "MAIL_ENCRYPTION=tls" >> .env
          echo "MAIL_FROM_ADDRESS=no-reply@scd.novemax.com.br" >> .env
          echo "MAIL_FROM_NAME=\"SCD Novemax\"" >> .env

          echo "JWT_SECRET=${{ secrets.ENV_JWT_KEY }}" >> .env
          echo "PIX_KEY=${{ secrets.ENV_PIX_KEY }}" >> .env
